# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 18:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_openinghours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openinghours',
            name='weekday',
        ),
        migrations.AddField(
            model_name='openinghours',
            name='end_weekday',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
        migrations.AddField(
            model_name='openinghours',
            name='start_weekday',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 3, 18, 53, 45, 175006, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 3, 18, 53, 54, 441582, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='uteservering',
            field=models.NullBooleanField(),
        ),
    ]
