# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20160704_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='neighbourhood',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='place',
            name='temporarily_closed_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='temporarily_closed_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='beer_price',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
