# Generated by Django 2.0.6 on 2018-07-17 15:50

import ajaximage.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgethak', '0014_place_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceUserEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('beer_price', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('beer_price_until', models.TimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('uteservering', models.NullBooleanField()),
                ('temporarily_closed_from', models.DateField(blank=True, null=True)),
                ('temporarily_closed_until', models.DateField(blank=True, null=True)),
                ('image', ajaximage.fields.AjaxImageField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_edits', to='budgethak.Place')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
