# Generated by Django 2.0.6 on 2018-07-19 18:28

from django.db import migrations

def migrate(apps, schema_editor):
    OpeningHours = apps.get_model('budgethak', 'OpeningHours')
    for oh in OpeningHours.objects.all():
        for weekday in range(oh.start_weekday+1, oh.end_weekday+1):
            oh_new = OpeningHours(
                place_id=oh.place_id,
                start_weekday=weekday, 
                opening_time=oh.opening_time, 
                closing_time=oh.closing_time,
                closed_entire_day=oh.closed_entire_day
            )
            oh_new.save()
            oh.end_weekday = oh.start_weekday
            oh.save()


class Migration(migrations.Migration):

    dependencies = [
        ('budgethak', '0016_openinghoursuseredit'),
    ]

    operations = [
        migrations.RunPython(migrate)
    ]
