# Generated by Django 2.0.6 on 2018-07-19 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgethak', '0018_auto_20180719_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openinghours',
            old_name='start_weekday',
            new_name='weekday',
        ),
        migrations.RenameField(
            model_name='openinghoursuseredit',
            old_name='start_weekday',
            new_name='weekday',
        ),
    ]
