# Generated by Django 2.0.6 on 2018-07-19 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgethak', '0019_auto_20180719_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghours',
            options={'ordering': ['weekday']},
        ),
        migrations.AlterModelOptions(
            name='openinghoursuseredit',
            options={'ordering': ['weekday']},
        ),
        migrations.RemoveField(
            model_name='openinghoursuseredit',
            name='place',
        ),
        migrations.AddField(
            model_name='openinghoursuseredit',
            name='place_user_edit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='budgethak.PlaceUserEdit'),
            preserve_default=False,
        ),
    ]
