# Generated by Django 2.0.6 on 2018-07-26 13:48

import budgethak.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgethak', '0022_auto_20180722_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeuseredit',
            name='merged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='placeuseredit',
            name='image',
            field=budgethak.fields.CustomAjaxImageField(blank=True, null=True),
        ),
    ]
